FROM  python:3.13-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["fastapi", "dev", "--host", "0.0.0.0"]

# gcloud auth login
# gcloud config set project gen-lang-client-0854258586
# gcloud config set run/region asia-south1
# gcloud run deploy SERVICE_NAME --source . --port 8080 --allow-unauthenticated --region=asia-south1

# gcloud run services delete fastapp --region=asia-south1
# gcloud artifacts repositories delete cloud-run-source-deploy --region=asia-south1
# gcloud run services describe fastapp --region=asia-south1
